name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонування репозиторію
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      # 2. Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Встановлення залежностей
      - name: Install dependencies 🔧
        run: npm ci

      # 4. Білд через Vite
      - name: Build project 🚀
        run: npm run build

      # 5. Деплой на GitHub Pages
      - name: Deploy to GitHub Pages 🌐
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages           # гілка для GitHub Pages
          folder: dist               # папка білду
          token: ${{ secrets.GITHUB_TOKEN }}

